### ISSUE TITLE
Backoff is not time warp safe because of erlang:now/0

### ISSUE THREAD

**Issue by silverblaze404** [ferd/backoff#26]
Need to ensure backoff is compatible with erlang otp 26 because it uses multi_time_warp by default:

Time warp safe code - https://www.erlang.org/doc/apps/erts/time_correction.html#time-warp-safe-code

**Comment by silverblaze404** [comment]
@ferd fyi

**Comment by ferd** [comment]
Reopening this. I was out at a conference last week and didn't have time to look at OSS stuff.

**Comment by ferd** [comment]
Ah I took a look. The use of `now()` is conditional to being on the old `random` module, which is contingent on using the OTP versions R12 to 17.0, and only to seed the PRNG. Since anything after that relies on the `rand` module which self-seeds, this does not require fixing.

Other time usage is hidden behind `erlang:start_timer/3`, which already relies on the new monotonic time functions, this is also safe to keep as is.

**Comment by silverblaze404** [comment]
Yeah, i realised it later that its using `erlang:now()` only in older OTP versions later. Thanks a lot :)
